### ISSUE TITLE
Support for 11.1.1.3

### ISSUE THREAD

**Issue by nwillemse** [agardiner/hfmcmd#22]
Hi Adam,

Is it possible to add support for 11.1.1.3?  Yea, I know, some of my clients are still on this version. Trying to get them to upgrade.  I dont see the build_for_11.1.1.3.bat file and don't know where to make all the changes.

I have an environment if you need me to test it.

Thanks
nick

**Comment by agardiner** [comment]
Hi Nick,
You should try the build for 9.3.1; I only produce a new build when there is a breaking change in the API, and to my knowledge, there is no breaking change between 9.3.1 and 11.1.2.1.
Let me know if you hit any issues with this build.

Cheers,
Adam
