### ISSUE TITLE
LoadJournals ERROR: 80040154

### ISSUE THREAD

**Issue by Mindaugas43** [agardiner/hfmcmd#23]
Hi Adam,
I'm getting an error while loading a Journal file 

ERROR  An error occurred while attempting to invoke command LoadJournals:
TargetInvocationException: Exception has been thrown by the target of an invocat
ion.
COMException: Retrieving the COM class factory for component with CLSID {BFBBA9C
1-28F0-11D3-BDA0-006008038DB4} failed due to the following error: 80040154.
FATAL  Exiting with status code 1

where could the issue be?
Thanks in advance.

**Comment by agardiner** [comment]
What version of HFM are you using? Do other commands work successfully?
You will need to provide a full error log to give me something to go on if you want any help.

**Comment by Mindaugas43** [comment]
Hi Adam, we're working on 11.1.2.3:500 version we've succesfully ran the HFM cosolidation, EA extract.
I'm happy to send the error log if needed i'm sending the screenshots from both log viewers in the cluster and the command line screenshot. It feels like it doesn't even invoke the functions in the  LoadJournals.dll

**Comment by Mindaugas43** [comment]
![Uploading Cluster_Node_1.JPG…]()
![Uploading Cluster_Node_2.JPG…]()
![Uploading Cmd.JPG…]()

**Comment by agardiner** [comment]
Your screenshots didn't come through...

**Comment by Mindaugas43** [comment]
Sorry there's something wrong it doesn't allow me to add images here can i send them directly to your email.

**Comment by agardiner** [comment]
I don't really need the screenshots - just the log output, which you can copy into the issue.

**Comment by Mindaugas43** [comment]
Command line output:

S:\Octon\Jobs\HFM>HFMCmd.exe LoadJournals
Enter a value for UserName (The user name to login with): admin
Enter a value for Password (The password to login with): ************
INFO   Executing Client command SetLogonInfo:
          UserName                 : admin
          Password                 : ******
Enter a value for Cluster (The name of the cluster on which to open the applicat
ion): Octon
Enter a value for Application (The name of the application to open): IHCDEV
INFO   Executing Connection command OpenApplication:
          Cluster                  : Octon
          Application              : IHCDEV
ERROR  An error occurred while attempting to invoke command LoadJournals:
TargetInvocationException: Exception has been thrown by the target of an invocat
ion.
COMException: Retrieving the COM class factory for component with CLSID {BFBBA9C
1-28F0-11D3-BDA0-006008038DB4} failed due to the following error: 80040154.
FATAL  Exiting with status code 1

S:\Octon\Jobs\HFM>HFMCmd.exe Consolidate
Enter a value for UserName (The user name to login with): admin
Enter a value for Password (The password to login with): ************
INFO   Executing Client command SetLogonInfo:
          UserName                 : admin
          Password                 : ******
Enter a value for Cluster (The name of the cluster on which to open the applicat
ion): Octon
Enter a value for Application (The name of the application to open): IHCDEV
INFO   Executing Connection command OpenApplication:
          Cluster                  : Octon
          Application              : IHCDEV
Enter a value for Scenarios (The scenario(s) in which to perform the consolidati
on): Actual
Enter a value for Years (The year(s) for which to perform the consolidation): 20
14
Enter a value for Periods (The period(s) over which the consolidation should be
performed): Jan
Enter a value for Entities (The entities for which the consolidation should be p
erformed): CUSO
INFO   Executing Calculate command Consolidate:
          Scenarios                : Actual
          Years                    : 2014
INFO   Consolidation completed: 0 performed, 1 not needed
INFO   Exiting with status code 0

S:\Octon\Jobs\HFM>HFMCmd.exe LoadJournals
Enter a value for UserName (The user name to login with): admin
Enter a value for Password (The password to login with): ************
INFO   Executing Client command SetLogonInfo:
          UserName                 : admin
          Password                 : ******
Enter a value for Cluster (The name of the cluster on which to open the applicat
ion): Octon
Enter a value for Application (The name of the application to open): IHCDEV
INFO   Executing Connection command OpenApplication:
          Cluster                  : Octon
          Application              : IHCDEV
ERROR  An error occurred while attempting to invoke command LoadJournals:
TargetInvocationException: Exception has been thrown by the target of an invocat
ion.
COMException: Retrieving the COM class factory for component with CLSID {BFBBA9C
1-28F0-11D3-BDA0-006008038DB4} failed due to the following error: 80040154.
FATAL  Exiting with status code 1

S:\Octon\Jobs\HFM>

**Comment by Mindaugas43** [comment]
There's nothing in the HFM logs as of Journal load, just the consolidation do you still need it ?

**Comment by agardiner** [comment]
OK, your error is because HFMCmd cannot instantiate the HsvJournalLoadACV COM component. This is part of the HFM client install; can you check if the client is installed on the machine you are running on? You should have a products/FinancialManagement/Client folder under your EPM_ORACLE_HOME folder.

If this folder is missing, you would still be able to connect and run consolidations, but you would not be able to load or extract data, journals, metadata, rules, or security.

**Comment by Mindaugas43** [comment]
There are only these dll's :
HFMConstants.dll
HfmSliceCOM.dll
HsvMetadataAPP.dll
HsvMetadataXML.dll
HsvResourceManager.dll
HsvStrindIDLib.dll
I'm guessing this is for the 64bit version because on the 32bit folder i can see all the dll's needed.

**Comment by agardiner** [comment]
Hmm... this is interesting.

It sounds like maybe you don't have a complete 64-bit installation of the client, since on my machine, all of the necessary files are in the Client folder, as well as the Client/32-bit folder.

When run on a 64-bit machine, HFMCmd will run as a 64-bit app, which means the .dll's it needs must be 64-bit as well.

What version of HFM are you running?

**Comment by Mindaugas43** [comment]
It's 64bit version

**Comment by agardiner** [comment]
No, I meant what version of HFM... 11.1.2.<?>?

**Comment by agardiner** [comment]
Oh - never mind - you already mentioned that much earlier.

**Comment by Mindaugas43** [comment]
I'll check the clusters this is an infrastructure issue not the HFMcmd.exe I  presume

**Comment by agardiner** [comment]
Yeah, it seems to be something with your environment.

I would try installing the HFM client on this machine, and see if that installs the missing 64-bit .dlls

**Comment by Mindaugas43** [comment]
Yeah i've found that it's the incomplete client installation, tried it on the server where the client is fully installed with all the dll's and it works perfectly fine. Thanks Adam for your help very much appreciated.

**Comment by agardiner** [comment]
OK, great - glad its working now.
