### ISSUE TITLE
Wait For Task

### ISSUE THREAD

**Issue by Mindaugas43** [agardiner/hfmcmd#25]
Hi Adam,
I wonder if you have some examples like let's say i need to disable logins for non admin users to an application and i want to wait till all the tasks will be completed in HFM. Is there such a functionality in HFMCmd.exe to set the timout for a running task ?

**Comment by agardiner** [comment]
If you are running tasks via HFMCmd, there should be no need to use the WaitForTask command to wait for them to finish - commands are executed in sequence, and block until they complete.
If you wish to wait for tasks started by other processes, you can use WaitForTask, but you need the task id of the task you want to wait for - this can be obtained via EnumTasks, but there is no facility to pass the output of this command into WaitForTask. Also, there is no facility to timeout the wait.
Not sure this is very helpful, but I'm also not really clear on what your use case is. What exactly are you trying to achieve?
Adam

**Comment by Mindaugas43** [comment]
I want to do a metadata load sequence, the first thing i want to do is take the HFM application offline  disable new logins and logout existing and wait for all the tasks to be completed. then do the metadata load. after the load i will bring hfm online.

**Comment by agardiner** [comment]
OK, what you want to do is certainly reasonable - but unfortunately, there is no way to do this at present.
It would be fairly simple to add a command to wait for all running tasks to complete; would you like to try it? Most of what you need is already available in src/hfm/SystemInfo.cs.

**Comment by Mindaugas43** [comment]
How about the logoff users and disable new logins is that doable ?

**Comment by frankdossing** [comment]
A normal procedure in our environment is simple to restart the environment and then startup everything except the web-layer. Then users are not able to start using HFM (or anything else), and you can do your load with no problem

**Comment by agardiner** [comment]
Sorry, there is no command implemented as yet for logging off users or preventing logins. These are both methods available on the Client COM object, and would not be difficult to add, but I no longer have a working HFM installation I can test this against.

**Comment by Mindaugas43** [comment]
Yeah i've checked the development guide for HFM and there is a dll that can do that. I'm just wondering if i can set your project in visual studio and just add the code, because i'm assuming you already have a reference to the dll. Or just modify the code and rebuild it again.

**Comment by frankdossing** [comment]
Are you sure logging out users are enough? What about running HSX processes on the HFM server? You could script your scenario using powershell and the HFMCMD tool - so restart server(s), start all HFM services, run Load, start web-services.

**Comment by Mindaugas43** [comment]
The sequence of this is that we disable new logins, logout the current non admin users, Enumerate all running tasks and wait for them to complete. That way we still have access to the application and we can do the metadata loads. Then we enable the logins. The restart of the HFM services is a on the list of the environmental sanity checks not on the automation piece.

**Comment by agardiner** [comment]
I've not setup the project for use in Visual Studio - but there are build scripts for building on any Windows machine without requiring VS.
The reference to the DLL is already there, as is a class for working with it - see src/hfm/Client.cs.

**Comment by Mindaugas43** [comment]
Hey Success Adam I've amended your script in the client.cs and it works now perfectly.
Thanks for the hint's, do you need the amended code ?

**Comment by agardiner** [comment]
That's great - glad you got it working.

If you want to send me a pull request, I'll merge your changes - they may be useful to others.

**Comment by Mindaugas43** [comment]
I think i'll add a couple of commands and will send you the pull request, as for now we can close this issue thanks for all the help.

**Comment by agardiner** [comment]
OK, but please make sure each command you add is a separate commit - its much harder to work with one big commit.
