### ISSUE TITLE
Cannot figure out how to buy Adam a beer

### ISSUE THREAD

**Issue by tnotm** [agardiner/hfmcmd#26]
My issue is not with the code.

I want to buy Adam a beer and I cannot find a donate button.

This is a great add to our community and I just want to say thanks.  HFMCmd has saved our shop from needing to use Task Flows, after already implementing them in the our extract design. To say it was simple to use HFMCmd to replace the extract Task Flows would be an understatement.

John

**Comment by agardiner** [comment]
John,
Thank you so much for taking the time to say thanks - it means a huge amount. I created this project to scratch an itch, and made it free because I thought it would be useful to others. It's very gratifying to hear that it has indeed been useful!
Cheers,
Adam
