### ISSUE TITLE
COMException Running Any Commands

### ISSUE THREAD

**Issue by justdan96** [agardiner/hfmcmd#27]
Hi,

We have an issue where if we try to run any commands in HFMCmd it produces a COM error like the below:

hfm> connect
ERROR  An error occurred while attempting to invoke command OpenApplication:
TargetInvocationException: Exception has been thrown by the target of an invocation.
TypeInitializationException: The type initializer for 'HFM.ResourceManager' threw an exception.
COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.

We are on HFM 11.1.2.3.500.

Thanks,

-Dan

**Comment by agardiner** [comment]
It sounds like an error is occurring right at start-up - are you trying to run this on a machine that has HFM installed?

**Comment by justdan96** [comment]
Installation issue, the DCOM configuration was incomplete.
