### ISSUE TITLE
Check HFM 11.1.2.3.701 compatibility

### ISSUE THREAD

**Issue by fdepedis** [agardiner/hfmcmd#28]
Hi Adam,

I have some problem to execute HFMCmd with "promote" functionality in HFM 11.1.2.3.701. The Warn Message that return is:
- WARN   Your version of HFM (11.1.2.3.701) may not be compatible with the version
  of HFM for which HFMCmd was built (11.1.2.3.0)
  and after a FATAL Error occur:
- FATAL  Exiting with status code 1

Do you know if HFMCmd run correctly in HFM 11.1.2.3.701 version ?

Thank you very for your help.
Regards
Flavio

**Comment by fdepedis** [comment]
Someone found some issue with this version?

**Comment by agardiner** [comment]
It sounds like the dispatch ids and/or method signature may have been changed in that patch release (sigh!). Unfortunately, I don't have access to this patch to determine if this is the case, or to build an updated binary that is compatible with this patch release.

You could attempt this yourself, but its not for the faint-hearted. It requires some familiarity with the TlbImp tool (in the tools directory of this project), Ruby and the Rake build tool, and the ability to read the existing code in the build script (Rakefile.rb) and understand what it is doing / what it needs.

As I no longer have a working HFM installation, I can't provide any real assistance with this. Apologies, but the real fault here lies with Oracle, who continually break API compatibility with new releases/patches.
